apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "app-spec-demo-mr"
  description: "Artifacts generator via Spec."
  annotations:
    github.com/project-slug: veecode-homolog/app-spec-demo-mr
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: publish.yml
    kong-manager/service-name: app.app-spec-demo-mr.80
    #app.app-spec-demo-mr.app-spec-demo-mr-service-0.80
    kong-manager/instance: /kong-manager/cluster-ec2-base-mr
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  providesApis:
    - app-spec-demo-mr
